### Create Deck
POST http://localhost:8080/api/decks
Content-Type: application/json

{
  "name": "name",
  "theme": "theme"
}

> {%
    client.test("Deck creation test", () => {
        client.assert(response.status === 200, "Status must be 200");
        client.log(response.body.deckId);
        client.global.set("deckId", response.body.deckId);
    });
%}

### Create Card
POST http://localhost:8080/api/cards
Content-Type: application/json

{
  "question": "question",
  "answer": "answer",
  "bucket": 1,
  "lastViewDate": "lastViewDate",
  "deckId": "{{deckId}}"
}

> {%
    client.test("Deck creation test", () => {
        client.assert(response.status === 200, "Status must be 200");
    });
%}
