server:
  port: 8080

springdoc:
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 1${server.port}

spring:
  data:
    mongodb:
      auto-index-creation: true