server:
  port: 8080

springdoc:
  show-actuator: true
  swagger-ui:
    oauth:
      realm: decker
      client-id: decker_api

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 1${server.port}

spring:
  data:
    mongodb:
      auto-index-creation: true
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8888/realms/decker

local-controller:
  enabled: true

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "Authorization"